### ISSUE TITLE
Simple Example

### ISSUE THREAD

**Issue by joernroeder** [coodoo/metalsmith-reactjs#1]
I tried to run the simple example (by copying the simple-example-folder into my new root)  but ran into two issues.
1. you should rename the package name in the example directory. Otherwise it will throw:
   `npm WARN install Refusing to install metalsmith-reactjs as a dependency of itself`
2. I'm getting an Error within the sass plugin.  `Arguments to path.join must be strings`. I've compiled the css myself and disabled the plugin for testing.

**Comment by coodoo** [comment]
Fixed.
